// <auto-generated />
namespace Emvisi.MigrationsBI
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GymInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GymInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "201610051538516_GymInitial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
